services:
  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # 管理介面
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - ./data:/var/lib/rabbitmq

networks:
  container_network:
    name: container_network
